[book]
authors = []
language = "en"
multilingual = false
src = "src"

[preprocessor]

[preprocessor.toc]
command = "mdbook-toc"

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[output]

[output.html]
#additional-css = ["mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
